version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: "http://13.210.218.7:5000"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: "mongodb+srv://hafsahphone3:eE3yvGZ2Ax_qH4y@book-store-mern.qmpya.mongodb.net/books-collection?retryWrites=true&w=majority&appName=Book-Store-Mern"
      PORT: "5000"
      NODE_ENV: "production"

volumes:
  mongodb_data: 